### ISSUE TITLE
32bit support

### ISSUE THREAD

**Issue by jamallx** [sgstair/tapdiag#1]
Hi @sgstair, if I wanted to get 32 bit working, would I just take the code and rebuild? You mentioned on IRC that you checked in the binary for reasons. Happy to help update while I am on the road if anything needs to change.

**Comment by sgstair** [comment]
Ah yes, there should be no problem building the code - I just don't normally like to check in binaries, did so here out of convenience and didn't anticipate running with 32bit (was mostly focused on server)

**Comment by sgstair** [comment]
(And let me know if you do have any trouble building for 32bit, and I'll take a closer look)

**Comment by sgstair** [comment]
I pushed a 32bit binary that should work. The build for it wasn't quite configured correctly, so there would have been some tweaking needed.
